name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

  # Build job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: gsheet.action
        uses: jroehl/gsheet.action@v2.1.0
        with:
          spreadsheetId: 1hKBf923bq8QndFwUUDXFhWTKyTeMS4ssIdB67BC29HI
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getSpreadsheet", "args": { "spreadsheetId": "${{ secrets.SPREDSHEET_ID }}" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
            
